USE DB_FUT;

--JOIN
SELECT
    *
FROM
    TB_JOGADORES tj
JOIN
    TB_JOGADORES_EQUIPE tje ON tj.ID_JOGADOR = tje.ID_JOGADOR
JOIN
    TB_EQUIPES te ON tje.ID_EQUIPE = te.ID_EQUIPE;

--LEFT JOIN
SELECT
    tj.NOME,
    te.NOME_EQUIPE
FROM
    TB_JOGADORES tj
LEFT JOIN
    TB_JOGADORES_EQUIPE tje ON tj.ID_JOGADOR = tje.ID_JOGADOR
LEFT JOIN
    TB_EQUIPES te ON tje.ID_EQUIPE = te.ID_EQUIPE;

--RIGHT JOIN
SELECT
    tj.NOME,
    te.NOME_EQUIPE
FROM
    TB_JOGADORES tj
RIGHT JOIN
    TB_JOGADORES_EQUIPE tje ON tj.ID_JOGADOR = tje.ID_JOGADOR
RIGHT JOIN
    TB_EQUIPES te ON tje.ID_EQUIPE = te.ID_EQUIPE;

--FULL JOIN
SELECT
    tj.NOME,
    te.NOME_EQUIPE
FROM
    TB_JOGADORES tj
FULL JOIN
    TB_JOGADORES_EQUIPE tje ON tj.ID_JOGADOR = tje.ID_JOGADOR
FULL JOIN
    TB_EQUIPES te ON tje.ID_EQUIPE = te.ID_EQUIPE;